[package]
name = "test_log"
version = "0.1.0"
authors = ["mswdwk <mswdwk@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
chrono = "0.4.6"
