[package]
name = "cache_test"
version = "0.1.0"
authors = ["mswdwk <mswdwk@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.1"
mempool = "0.3.1"